platform :ios, '10.0'
use_frameworks!

target 'Collor_Example' do
  pod 'Collor', :path => '../'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'Collor_Tests' do
    inherit! :search_paths

    pod 'CwlPreconditionTesting', :git => 'https://github.com/mattgallagher/CwlPreconditionTesting.git'
	pod 'CwlCatchException', :git => 'https://github.com/mattgallagher/CwlCatchException.git'

    
  end
end
